# Generated by Django 3.1.4 on 2020-12-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=500)),
                ('mock_no', models.IntegerField()),
                ('mock', models.JSONField(default=dict)),
            ],
        ),
    ]
